<?php

$_SERVER["DOCUMENT_ROOT"]=dirname(__FILE__) . "/../public_html";
include('../public_html/app-start.php');

$oCLI=new cbframe_cli_helper($GLOBALS["arrCBFApplicationVariables"]["system_monitor_emails_to"]);
$oCLI->boolSuppressEcho=false;
$oCLI->enable_echo_logging();
$oCLI->ensure_cli_context();

$arrStats["hosts_allow_page"]="/hosts-allow.htm"; //Ensure that this page requires login
$arrStats["hosts_allow_file"]="/etc/hosts.allow";
$arrStats["hosts_allow_start_tag"]="# ####### hosts.allow.root.script.php SECTION START ########";
$arrStats["hosts_allow_end_tag"]="# ####### hosts.allow.root.script.php SECTION END ########";

$arrStats["hosts_allow_file_contents"]=ReadTextFile($arrStats["hosts_allow_file"],$strError);

if (!$arrStats["hosts_allow_file_contents"]){
	$oCLI->death($strError);
}

$lngStartPos=strpos($arrStats["hosts_allow_file_contents"],$arrStats["hosts_allow_start_tag"]);

if ($lngStartPos===false){
	$oCLI->death("File " . $arrStats["hosts_allow_file"] . " is missing Start Tag: " . $arrStats["hosts_allow_start_tag"] );
}

$lngEndPos=strpos($arrStats["hosts_allow_file_contents"],$arrStats["hosts_allow_end_tag"]);

if ($lngEndPos===false){
	$oCLI->death("File " . $arrStats["hosts_allow_file"] . " is missing End Tag: " . $arrStats["hosts_allow_end_tag"] );
}

$arrEntries=array();

$sql="SELECT userid,max(LOG_ID) as LOG_ID,max(LOG_DATE) as LOG_DATE  FROM http_log 
WHERE userid IS NOT NULL
AND REQUEST_URI LIKE '" . $arrStats["hosts_allow_page"] . "%' GROUP BY userid";

$arrLogs=$db->GetAssoc($sql);

foreach($arrLogs as $arrLog){
	
	$sql="SELECT * FROM users WHERE userid=" . $db->qstr($arrLog["userid"]);
	
	$arrUser=$db->GetRow($sql);
	
	if (stripos($arrUser["permissions"],"|9|")===false && stripos($arrUser["permissions"],"|1|")===false ){
		$oCLI->d_echo($arrUser["display_name"] . " does not have permission");
		continue;
	}
	
	
	$sql="SELECT * FROM http_log WHERE LOG_ID=" . $db->qstr($arrLog["LOG_ID"]);
	
	$arrLastLog=$db->GetRow($sql);
	

	$oCLI->d_echo($arrUser["display_name"] . " LAST IP: " . $arrLastLog["REMOTE_ADDR"]);
	
	$arrUser["LAST_REMOTE_ADDR"]=$arrLastLog["REMOTE_ADDR"];
	
	$arrEntries[$arrUser["userid"]]=$arrUser;
	
	
}

$s="\n# THIS SECTION HAS BEEN AUTO GENERATED BY SCRIPT\n";

foreach($arrEntries as $arrEntry){
	
	$strSafeDisplayName=str_replace("#","",$arrEntry["display_name"]);
	$strSafeDisplayName=str_replace("\n","",$strSafeDisplayName);
	$strSafeDisplayName=str_replace("\r","",$strSafeDisplayName);
	
	$s .="\n# " . $strSafeDisplayName;
	$s .="\nsshd : " . $arrEntry["LAST_REMOTE_ADDR"] . " : allow\n\n";
	
}


$arrStats["hosts_allow_new_file_contents"]=substr($arrStats["hosts_allow_file_contents"],0,($lngStartPos + strlen($arrStats["hosts_allow_start_tag"])));

$arrStats["hosts_allow_new_file_contents"] .=$s;

$arrStats["hosts_allow_new_file_contents"] .=substr($arrStats["hosts_allow_file_contents"],$lngEndPos);



if (!WriteTextFile($arrStats["hosts_allow_file"],$arrStats["hosts_allow_new_file_contents"],$strError)){
	$oCLI->death($strError);
}

//Stop emails from being sent on success as this script should get run every minute
$oCLI->strAdminEmail="";

$oCLI->end($oCLI->pretty_array($arrStats));

?>